export const StorageAddress = "0xdc399e1c91d244608f986d870568f1f6855e3975";
export const abi = [
  { type: "constructor", stateMutability: "nonpayable", inputs: [] },
  { type: "fallback", stateMutability: "payable" },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "addPostHash",
    inputs: [{ type: "string", name: "_postHash", internalType: "string" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "admins",
    inputs: [{ type: "address", name: "", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "deletePostHash",
    inputs: [{ type: "string", name: "_postHash", internalType: "string" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "string[]", name: "", internalType: "string[]" }],
    name: "getAllPostsHashes",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "index",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "indexes",
    inputs: [{ type: "string", name: "", internalType: "string" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "makeAdmin",
    inputs: [
      { type: "address", name: "_toMakeAdmin", internalType: "address" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "owner",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "string", name: "", internalType: "string" }],
    name: "postsHashes",
    inputs: [{ type: "uint256", name: "", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "removeAdmin",
    inputs: [
      { type: "address", name: "_toRemoveAdmin", internalType: "address" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setNewPostHashAfterEdit",
    inputs: [
      { type: "string", name: "_newPostHash", internalType: "string" },
      { type: "string", name: "_oldPostHash", internalType: "string" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "withDraw",
    inputs: [
      { type: "uint256", name: "_amount", internalType: "uint256" },
      { type: "address", name: "_to", internalType: "address" },
    ],
  },
  { type: "receive", stateMutability: "payable" },
];
